---
title: "Unsupervised Analysis"
author: "Lizzy Gibson"
date: "April 29, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(stringr)
library(forcats)
library(rvest)
library(httr)
library(janitor)
library(leaflet)
library(reshape2)
library(ISLR)
```

## PCA

```{r data}
#remove outcome and confounders from PCA matrix
unsup <- data %>% select(-resp, -day_of_week, -outdoor_temperature, -relative_humidity)
#make date rowname
unsup <- unsup %>% as.data.frame() %>% column_to_rownames(var = "date")
```

```{r}
pr.out <- prcomp(~ ., unsup, scale = TRUE, na.action = na.omit)
names(pr.out)

pr.out$center

pr.out$scale

pr.out$rotation
# The kth column is the kth loading vector (phi)

dim(pr.out$x)
head(pr.out$x)
# The kth column is the kth PC score vector (z)

biplot(pr.out, scale = 0)
# scale=0: the arrows are scaled to represent the loadings

# The PCs are only unique up to a sign change
pr.out$rotation = -pr.out$rotation
pr.out$x = -pr.out$x
biplot(pr.out, scale = 0)

pr.out$sdev
# the standard deviation of each PC

pr.var = pr.out$sdev^2
pr.var
# variance explained by each PC


pve = pr.var/sum(pr.var)
pve
# PVE

plot(pve, xlab = "Principal Component", 
     ylab = "Proportion of Variance Explained", ylim = c(0,1), type = 'b')

plot(cumsum(pve), xlab = "Principal Component", 
     ylab="Cumulative Proportion of Variance Explained", ylim = c(0,1), type = 'b')
a = c(1,2,8,-3)
cumsum(a)

```

